### ISSUE TITLE
Background playback does not work when you set the player on an existing BMPBitmovinPlayerView

### ISSUE THREAD

**Issue by jordanhbuiltbyhq** [bitmovin/bitmovin-player-ios-sdk-cocoapod#15]
If you take the [BackgroundPlayback sample app](https://github.com/bitmovin/bitmovin-player-ios-samples/tree/master/BackgroundPlayback) and modify it to place the BMPBitmovinPlayerView in the storyboard instead of programmatically creating it, then you assign the player to the existing player view, you'll find the audio pauses when you close the app - it for some reason no longer supports background playback. This tripped me up for a long time in our app before I finally figured out it was because I didn't programmatically create the player view.

To reproduce, simply add a UIView to Main.storyboard and switch its class to BMPBitmovinPlayerView, create an IBOutlet for it, then replace
`let playerView = BMPBitmovinPlayerView(player: player, frame: .zero)`
with
`playerView.player = player`
and then of course remove

```swift
playerView.autoresizingMask = [.flexibleHeight, .flexibleWidth]
playerView.frame = view.bounds

view.addSubview(playerView)
view.bringSubviewToFront(playerView)
```
Now when you close the app it does not play in the background.

**Comment by soberman** [comment]
Hi! Thank you for reporting. We could reproduce the behavior and will fix it with one of the upcoming releases. I'll let you know as soon as this happened.

**Comment by dweinber** [comment]
Hi,
Should this still be a valid issue for you, please create a support ticket via your dedicated ticketing system should you have access to one or via https://bitmovin.com/dashboard/support/tickets otherwise.

Please also keep in mind that this repository is deprecated, please update your project to use our up to date Cocoapods spec repository: https://github.com/bitmovin/cocoapod-specs
