### ISSUE TITLE
Mute when using AirPlay 

### ISSUE THREAD

**Issue by jordanhbuiltbyhq** [bitmovin/bitmovin-player-ios-sdk-cocoapod#20]
We're seeing when you mute the Bitmovin player while streaming via AirPlay, it appears to mute but audio is still audible through the AirPlay speaker(s). This is reproducible in the AirPlay sample project:
1) Connect via AirPlay
2) Play the video
3) Tap the mute button
Result: Mute button appears muted yet audio still is heard

**Comment by stonko1994** [comment]
I looked into this issue but I was not able to reproduce this issue.

Can you please specify your versions of iOS / tvOS and also the AppleTV model version.

**Comment by jordanhbuiltbyhq** [comment]
Sure thing. I'm using iOS 13.0 on iPad Pro and iOS 13.1 on iPhone X AirPlaying to a HomePod, with sdk 2.30.0.

**Comment by jeffchandler30** [comment]
I have a iPhone 6 on version 12.4 which experiences this issue.   Another iPhone 7 also on 12.4 which has this issue.   I'm playing to a Sonos One.

**Comment by stonko1994** [comment]
Thanks, we will look into it.

**Comment by dweinber** [comment]
Hi,
Should this still be a valid issue for you, please create a support ticket via your dedicated ticketing system should you have access to one or via https://bitmovin.com/dashboard/support/tickets otherwise.

Please also keep in mind that this repository is deprecated, please update your project to use our up to date Cocoapods spec repository: https://github.com/bitmovin/cocoapod-specs
