### ISSUE TITLE
Translations for ad buttons

### ISSUE THREAD

**Issue by buscarini** [bitmovin/bitmovin-player-ios-sdk-cocoapod#24]
Is there a way to translate the ad buttons? I mean the "Learn more" and the "Skip" labels. I've checked the documentation but I'm unable to find a way to do this.

**Comment by dweinber** [comment]
Hi,

You can use the [AdvertisingConfig.beforeInitialization](https://cdn.bitmovin.com/player/ios/3/docs/Classes/BMPAdvertisingConfig.html#/c:objc(cs)BMPAdvertisingConfig(py)beforeInitialization) callback to set the `language` (please see the IMA SDK doc for language options: https://developers.google.com/interactive-media-ads/docs/sdks/ios/client-side/localization)

Should this not resolve your problem, please create a support ticket via your dedicated ticketing system should you have access to one or via https://bitmovin.com/dashboard/support/tickets otherwise.

Please also keep in mind that this repository is deprecated, please update your project to use our up to date Cocoapods spec repository: https://github.com/bitmovin/cocoapod-specs
