### ISSUE TITLE
Duration can be infinity

### ISSUE THREAD

**Issue by hipwelljo** [bitmovin/bitmovin-player-ios-sdk-cocoapod#25]
We're seeing some crashes in our app due to the player reporting its duration is +inf. To replicate this issue:

1. Open the BasicPlayback example project
2. Replace the URL with [this one](https://hotmic-content.s3-us-west-1.amazonaws.com/recordings/frank-4901/de5f9586-6f94-42d1-99d9-de9964323bf3/playlist.m3u8)
3. Run the app

You'll notice `onDurationChanged inf` is logged to the console. If you let it sit for a minute you'll see `onError General playback error. Stream ended unexpectedly.`

**Comment by dweinber** [comment]
Hi,
Should this still be a valid issue for you, please create a support ticket via your dedicated ticketing system should you have access to one or via https://bitmovin.com/dashboard/support/tickets otherwise.

Please also keep in mind that this repository is deprecated, please update your project to use our up to date Cocoapods spec repository: https://github.com/bitmovin/cocoapod-specs
