### ISSUE TITLE
Swift Package Manager Support

### ISSUE THREAD

**Issue by ivanlisovyi** [bitmovin/bitmovin-player-ios-sdk-cocoapod#27]
Hi, 

Do you have plans to add a support for the Swift Package Manager to the SDK anytime soon? If yes, will you be able to provide an ETA? 

Thanks!

**Comment by dweinber** [comment]
We looking for customer interest in this and are tracking this internally. However, we currently don't have near-term plans to add support for it.

Please feel free to create a support ticket via your dedicated ticketing system should you have access to one or via https://bitmovin.com/dashboard/support/tickets otherwise.

Please also keep in mind that this repository is deprecated, please update your project to use our up to date Cocoapods spec repository: https://github.com/bitmovin/cocoapod-specs

**Comment by dweinber** [comment]
@ivanlisovyi I just wanted to let you know that Swift Package Manager is supported for the Bitmovin Player as of today.
