### ISSUE TITLE
Unable to exit full screen during pre/post roll ad

### ISSUE THREAD

**Issue by MatejBalantic** [bitmovin/bitmovin-player-ios-sdk-cocoapod#8]
When the player is playing a pre-roll or post-roll add, the full-screen button becomes hidden.

As a result, a user can not exit full-screen mode when an ad is playing.

The only way for the user to recover is to wait until the end of the ad or kill the app.

![simulator screen shot - iphone x - 2018-07-11 at 11 42 24](https://user-images.githubusercontent.com/994179/42563842-7e3e4e18-84ff-11e8-8bec-c86ac0f4764b.png)

cc @samek

**Comment by hawk23** [comment]
Thank you for reporting. We could reproduce the behavior and will fix it with one of the upcoming releases. I'll notify you as soon as this happened.

**Comment by dweinber** [comment]
Hi,
Should this still be a valid issue for you, please create a support ticket via your dedicated ticketing system should you have access to one or via https://bitmovin.com/dashboard/support/tickets otherwise.

Please also keep in mind that this repository is deprecated, please update your project to use our up to date Cocoapods spec repository: https://github.com/bitmovin/cocoapod-specs
